ci:
  autofix_prs: false
  skip: ["mypy"]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
        language_version: python3.13
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args:
          [
            "--disable-plugin",
            "HexHighEntropyString",
            "--disable-plugin",
            "Base64HighEntropyString",
          ]
        exclude: tests/pre_award/keys/rsa256

  - repo: local
    hooks:
      - id: mypy
        name: Run type checks
        language: system
        types: [python]
        entry: uv run mypy
        pass_filenames: false
      - id: format-html
        name: Format HTML with prettier
        language: system
        types: [text]
        files: \.html$
        entry: bash -c "if docker compose ps --services --filter 'status=running' | grep funding-service; then docker compose exec -T --rm funding-service make format-html; else docker compose run -T funding-service make format-html; fi"
