services:
  db:
    image: postgres:16@sha256:301bcb60b8a3ee4ab7e147932723e3abd1cef53516ce5210b39fd9fe5e3602ae
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  # pragma: allowlist secret
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ofs

  funding-service:
    build: .
    init: true
    volumes:
      - .:/app
      - /app/node_modules
      - '/app/.venv' # Don't overwrite this directory with local .venv because uv links won't translate in the container
    ports:
      - "5173:5173" # vite server
      - "8080:8080" # application
      - "8081:8081" # debugpy
    stdin_open: true
    tty: true
    command: > # The single & on line 33 puts vite into background mode so it doesn't take over the logs
      bash -c "

      uv run flask db upgrade && \
      uv run flask developers seed-grants

      npm run dev -- --host &
      PYDEVD_DISABLE_FILE_VALIDATION=1 python -m debugpy --listen 0.0.0.0:8081 -m flask run --host 0.0.0.0 --port 8080
      "
    environment:
      SECRET_KEY: pretend_secret_key  #pragma: allowlist secret
      FLASK_APP: app
      FLASK_ENV: local
      DATABASE_HOST: "db"
      DATABASE_PORT: 5432
      DATABASE_NAME: "postgres"
      DATABASE_SECRET: '{"username":"postgres","password":"postgres"}'  # pragma:allowlist secret
      AZURE_AD_BASE_URL: http://sso.communities.gov.localhost/
    depends_on:
      - db
    networks:
      - ofs

  sso:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
      - '/app/.venv' # Don't overwrite this directory with local .venv because uv links won't translate in the container
    ports:
      - "4005:4005" # application
    stdin_open: true
    tty: true
    command: >
      bash -c "
      uv run flask run --host 0.0.0.0 --port 4005 --debug
      "
    environment:
      FLASK_APP: "stubs.sso:create_sso_stub_app"
      WERKZEUG_DEBUG_PIN: off
      ASSETS_VITE_LIVE_ENABLED: true
      FLASK_ENV: local
    networks:
      ofs:
        aliases:
          - sso.communities.gov.localhost

volumes:
  postgres_data:
  localstack_data:

networks:
  ofs:
