services:
  # use Caddy for SSL termination
  proxy:
    image: caddy:2
    restart: unless-stopped
    command: "caddy run --config /etc/caddy/Caddyfile"
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .pullpreview/Caddyfile:/etc/caddy/Caddyfile
      - "/data"
    networks:
      - ofs

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  # pragma: allowlist secret
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ofs

  web:
    build: .
    volumes:
      - .:/app
      - '/app/.venv' # Don't overwrite this directory with local .venv because uv links won't translate in the container
    ports:
      - "8080"
    stdin_open: true
    tty: true
    command: flask run --host 0.0.0.0 --port 8080
    environment:
      FLASK_ENV: dev
      FLASK_PORT: 8080
      DATABASE_URI: "postgresql+psycopg://postgres:postgres@db:5432/postgres"  # pragma: allowlist secret
      SERVER_NAME: web:8080
      SECRET_KEY: unsafe  # pragma: allowlist secret
      DEBUG_TB_ENABLED: true
    depends_on:
      - db
    networks:
      - ofs

volumes:
  postgres_data:

networks:
  ofs:
