CHECK_YOUR_ANSWERS = "check-your-answers"

DATA_SET_EXTERNAL_ID_COLUMN_HEADER = "Organisation ID"
DATA_SET_GRANT_RECIPIENT_COLUMN_HEADER = "Grant recipient"
DATA_SET_IDENTIFIER_COLUMN_HEADERS = [DATA_SET_EXTERNAL_ID_COLUMN_HEADER, DATA_SET_GRANT_RECIPIENT_COLUMN_HEADER]
