import datetime

CHECK_YOUR_ANSWERS = "check-your-answers"

DATA_SET_EXTERNAL_ID_COLUMN_HEADER = "Organisation ID"
DATA_SET_GRANT_RECIPIENT_COLUMN_HEADER = "Grant recipient"
DATA_SET_IDENTIFIER_COLUMN_HEADERS = [DATA_SET_EXTERNAL_ID_COLUMN_HEADER, DATA_SET_GRANT_RECIPIENT_COLUMN_HEADER]
BRITISH_POUNDS_PREFIX = "£"
BRITISH_POUNDS_DECIMAL_PLACES = 2
DATA_SET_PREVIEW_LENGTH = 3
HARD_SUBMISSION_DEADLINE_TIME = datetime.time(hour=14)
HARD_SUBMISSION_DEADLINE_TIME_DISPLAY = HARD_SUBMISSION_DEADLINE_TIME.strftime("%-I%p").lower()

SESSION_DATA_SET_UPLOAD = "data_set_upload"
SESSION_DATA_SET_REPLACE = "data_set_replace"

SESSION_SIGNING_UP_FOR_COLLECTION_ID = "signing_up_for_collection_id"
SESSION_CREATE_ORGANISATION = "create_organisation"
SESSION_MATCHED_ORGANISATION = "matched_organisation"
SESSION_EMITTED_PUBLIC_SIGN_UP_METRICS = "emitted_public_sign_up_metrics"
