CHECK_YOUR_ANSWERS = "check-your-answers"

DATA_SET_EXTERNAL_ID_COLUMN_HEADER = "Organisation ID"
DATA_SET_GRANT_RECIPIENT_COLUMN_HEADER = "Grant recipient"
DATA_SET_IDENTIFIER_COLUMN_HEADERS = [DATA_SET_EXTERNAL_ID_COLUMN_HEADER, DATA_SET_GRANT_RECIPIENT_COLUMN_HEADER]
BRITISH_POUNDS_PREFIX = "£"
BRITISH_POUNDS_DECIMAL_PLACES = 2
DATA_SET_PREVIEW_LENGTH = 3

SESSION_DATA_SET_UPLOAD = "data_set_upload"
SESSION_DATA_SET_REPLACE = "data_set_replace"
