"""empty message

Revision ID: 002_wip_add_another
Revises: 001_reset_migrations
Create Date: 2025-09-18 12:33:30.385065

"""

import sqlalchemy as sa
from alembic import op

revision = "002_wip_add_another"
down_revision = "001_reset_migrations"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("component", schema=None) as batch_op:
        batch_op.add_column(sa.Column("add_another", sa.Boolean(), server_default="false", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("component", schema=None) as batch_op:
        batch_op.drop_column("add_another")

    # ### end Alembic commands ###
