"""Add detailed fields to grant table including GGIS number, description, and primary contact information, to support
the new grant setup flow.

Revision ID: 004_add_detailed_grant_fields
Revises: 003_nulls_not_distinct_user_role
Create Date: 2025-05-28 12:28:03.638441

"""

import sqlalchemy as sa
from alembic import op

revision = "004_add_detailed_grant_fields"
down_revision = "003_nulls_not_distinct_user_role"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grant", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ggis_number", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("description", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("primary_contact_name", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("primary_contact_email", sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grant", schema=None) as batch_op:
        batch_op.drop_column("primary_contact_email")
        batch_op.drop_column("primary_contact_name")
        batch_op.drop_column("description")
        batch_op.drop_column("ggis_number")

    # ### end Alembic commands ###
