"""Add UTC Suffix

Revision ID: 005_add_utc_suffix
Revises: 004_user_and_magic_links
Create Date: 2025-04-30 09:33:10.478935

"""

from alembic import op

revision = "005_add_utc_suffix"
down_revision = "004_user_and_magic_links"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grant", schema=None) as batch_op:
        batch_op.alter_column(column_name="created_at", new_column_name="created_at_utc")
        batch_op.alter_column(column_name="updated_at", new_column_name="updated_at_utc")

    with op.batch_alter_table("magic_link", schema=None) as batch_op:
        batch_op.alter_column(column_name="created_at", new_column_name="created_at_utc")
        batch_op.alter_column(column_name="updated_at", new_column_name="updated_at_utc")

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(column_name="created_at", new_column_name="created_at_utc")
        batch_op.alter_column(column_name="updated_at", new_column_name="updated_at_utc")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(column_name="created_at_utc", new_column_name="created_at")
        batch_op.alter_column(column_name="updated_at_utc", new_column_name="updated_at")

    with op.batch_alter_table("magic_link", schema=None) as batch_op:
        batch_op.alter_column(column_name="created_at_utc", new_column_name="created_at")
        batch_op.alter_column(column_name="updated_at_utc", new_column_name="updated_at")

    with op.batch_alter_table("grant", schema=None) as batch_op:
        batch_op.alter_column(column_name="created_at_utc", new_column_name="created_at")
        batch_op.alter_column(column_name="updated_at_utc", new_column_name="updated_at")

    # ### end Alembic commands ###
