"""empty message

Revision ID: 006_add_collection_schema
Revises: 005_add_utc_suffix
Create Date: 2025-05-01 14:09:37.627826

"""

import sqlalchemy as sa
from alembic import op

revision = "005_add_collection_schema"
down_revision = "005_add_utc_suffix"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schema",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("grant_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["user.id"], name=op.f("fk_schema_created_by_id_user")),
        sa.ForeignKeyConstraint(["grant_id"], ["grant.id"], name=op.f("fk_schema_grant_id_grant")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schema")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("schema")
    # ### end Alembic commands ###
