"""empty message

Revision ID: 007_schema_unique_constraint
Revises: 006_add_collection_schema
Create Date: 2025-05-02 10:08:21.080685

"""

from alembic import op

revision = "007_schema_unique_constraint"
down_revision = "006_add_collection_schema"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("schema", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_schema_name_grant_id", ["name", "grant_id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("schema", schema=None) as batch_op:
        batch_op.drop_constraint("uq_schema_name_grant_id", type_="unique")

    # ### end Alembic commands ###
