"""empty message

Revision ID: 007_wip
Revises: 006_add_collection_schema
Create Date: 2025-05-15 17:45:04.499998

"""

import sqlalchemy as sa
from alembic import op

revision = "007_wip"
down_revision = "006_add_collection_schema"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "section",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at_utc", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("collection_schema_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_schema_id"],
            ["collection_schema.id"],
            name=op.f("fk_section_collection_schema_id_collection_schema"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_section")),
        sa.UniqueConstraint(
            "order", "collection_schema_id", deferrable=True, name="uq_section_order_collection_schema"
        ),
        sa.UniqueConstraint("title", "collection_schema_id", name="uq_section_title_collection_schema"),
    )
    op.create_table(
        "form",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at_utc", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("section_id", sa.Uuid(), nullable=False),
        sa.Column("collection_schema_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_schema_id"],
            ["collection_schema.id"],
            name=op.f("fk_form_collection_schema_id_collection_schema"),
        ),
        sa.ForeignKeyConstraint(["section_id"], ["section.id"], name=op.f("fk_form_section_id_section")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_form")),
        sa.UniqueConstraint("order", "section_id", deferrable=True, name="uq_form_order_section"),
        sa.UniqueConstraint("slug", "section_id", name="uq_form_slug_section"),
        sa.UniqueConstraint("title", "collection_schema_id", name="uq_form_title_collection_schema"),
    )
    op.create_table(
        "question",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at_utc", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("hint", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("data_type", sa.String(), nullable=False),
        sa.Column("form_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["form_id"], ["form.id"], name=op.f("fk_question_form_id_form")),
        sa.ForeignKeyConstraint(["parent_id"], ["question.id"], name=op.f("fk_question_parent_id_question")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question")),
        sa.UniqueConstraint("name", "form_id", name="uq_question_name_form"),
        sa.UniqueConstraint("order", "parent_id", "form_id", deferrable=True, name="uq_question_order_parent_form"),
        sa.UniqueConstraint("slug", "form_id", name="uq_question_slug_form"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("question")
    op.drop_table("form")
    op.drop_table("section")
    # ### end Alembic commands ###
