"""empty message

Revision ID: 008_wip
Revises: 007_wip
Create Date: 2025-05-19 14:33:43.047572

"""

import sqlalchemy as sa
from alembic import op

revision = "008_wip"
down_revision = "007_wip"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("submission_event", schema=None) as batch_op:
        batch_op.add_column(sa.Column("form_id", sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(batch_op.f("fk_submission_event_form_id_form"), "form", ["form_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("submission_event", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_submission_event_form_id_form"), type_="foreignkey")
        batch_op.drop_column("form_id")

    # ### end Alembic commands ###
