"""empty message

Revision ID: 009_wip_depends_on
Revises: 008_wip
Create Date: 2025-05-22 11:08:33.173144

"""

import sqlalchemy as sa
from alembic import op

revision = "009_wip_depends_on"
down_revision = "008_wip"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question_depends_on",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at_utc", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("depends_on_question_id", sa.Uuid(), nullable=False),
        sa.Column("expression_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["depends_on_question_id"],
            ["question.id"],
            name=op.f("fk_question_depends_on_depends_on_question_id_question"),
        ),
        sa.ForeignKeyConstraint(
            ["expression_id"], ["expression.id"], name=op.f("fk_question_depends_on_expression_id_expression")
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["question.id"], name=op.f("fk_question_depends_on_question_id_question")
        ),
        sa.PrimaryKeyConstraint("id", "question_id", "depends_on_question_id", name=op.f("pk_question_depends_on")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("question_depends_on")
    # ### end Alembic commands ###
