"""empty message

Revision ID: 010_wip_squash_message
Revises: 009_wip_depends_on
Create Date: 2025-05-22 13:40:38.908193

"""

import sqlalchemy as sa
from alembic import op

revision = "010_wip_squash_message"
down_revision = "009_wip_depends_on"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expression", schema=None) as batch_op:
        batch_op.add_column(sa.Column("human_readable_message", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expression", schema=None) as batch_op:
        batch_op.drop_column("human_readable_message")

    # ### end Alembic commands ###
