"""empty message

Revision ID: 011_wip_squash_optional
Revises: 010_wip_squash_message
Create Date: 2025-05-22 13:54:52.282494

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "011_wip_squash_optional"
down_revision = "010_wip_squash_message"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question", schema=None) as batch_op:
        batch_op.alter_column("text", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "data_type",
            existing_type=postgresql.ENUM(
                "SINGLE_LINE_OF_TEXT", "MULTIPLE_LINES_OF_TEXT", "UK_ADDRESS", name="datatype"
            ),
            nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question", schema=None) as batch_op:
        batch_op.alter_column(
            "data_type",
            existing_type=postgresql.ENUM(
                "SINGLE_LINE_OF_TEXT", "MULTIPLE_LINES_OF_TEXT", "UK_ADDRESS", name="datatype"
            ),
            nullable=False,
        )
        batch_op.alter_column("text", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###
