"""empty message

Revision ID: 012_wip_squash_nullable
Revises: 011_wip_squash_optional
Create Date: 2025-05-23 13:44:41.234230

"""

import sqlalchemy as sa
from alembic import op

revision = "012_wip_squash_nullable"
down_revision = "011_wip_squash_optional"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question", schema=None) as batch_op:
        batch_op.alter_column("form_id", existing_type=sa.UUID(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question", schema=None) as batch_op:
        batch_op.alter_column("form_id", existing_type=sa.UUID(), nullable=False)

    # ### end Alembic commands ###
