"""empty message

Revision ID: 017_do_it
Revises: 016_do_it
Create Date: 2025-07-08 21:28:42.391902

"""

from alembic import op
from alembic_postgresql_enum import TableReference

revision = "017_do_it"
down_revision = "016_do_it"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="managed_expression_enum",
        new_values=[
            "GREATER_THAN",
            "LESS_THAN",
            "BETWEEN",
            "CHOICE_FROM_LIST",
            "SINGLE_CHOICE_FROM_LIST",
            "ALL_CHOICES_FROM_LIST",
        ],
        affected_columns=[TableReference(table_schema="public", table_name="expression", column_name="managed_name")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="managed_expression_enum",
        new_values=["GREATER_THAN", "LESS_THAN", "BETWEEN", "CHOICE_FROM_LIST"],
        affected_columns=[TableReference(table_schema="public", table_name="expression", column_name="managed_name")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
