"""empty message

Revision ID: 019_do_it
Revises: 018_do_it
Create Date: 2025-07-09 15:24:58.285969

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "019_do_it"
down_revision = "018_do_it"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_source_choice",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at_utc", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("data_source_id", sa.Uuid(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["data_source_id"], ["data_source.id"], name=op.f("fk_data_source_choice_data_source_id_data_source")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_source_choice")),
        sa.UniqueConstraint("data_source_id", "key", name="uq_data_source_id_key"),
        sa.UniqueConstraint("data_source_id", "order", deferrable=True, name="uq_data_source_id_order"),
    )
    with op.batch_alter_table("data_source", schema=None) as batch_op:
        batch_op.drop_column("used_choice_ids")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("data_source", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("used_choice_ids", postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False)
        )

    op.drop_table("data_source_choice")
    # ### end Alembic commands ###
