"""empty message

Revision ID: 020_do_it
Revises: 019_do_it
Create Date: 2025-07-09 15:35:49.056001

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "020_do_it"
down_revision = "019_do_it"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("data_source", schema=None) as batch_op:
        batch_op.drop_column("data")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("data_source", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False)
        )

    # ### end Alembic commands ###
