"""empty message

Revision ID: 021_do_it
Revises: 020_do_it
Create Date: 2025-07-09 17:48:44.151496

"""

import sqlalchemy as sa
from alembic import op

revision = "021_do_it"
down_revision = "020_do_it"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_source_choice_reference",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at_utc", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("data_source_choice_id", sa.Uuid(), nullable=False),
        sa.Column("expression_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["data_source_choice_id"],
            ["data_source_choice.id"],
            name=op.f("fk_data_source_choice_reference_data_source_choice_id_data_source_choice"),
        ),
        sa.ForeignKeyConstraint(
            ["expression_id"], ["expression.id"], name=op.f("fk_data_source_choice_reference_expression_id_expression")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_source_choice_reference")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data_source_choice_reference")
    # ### end Alembic commands ###
