"""empty message

Revision ID: 036_adding_add_another_max_int_column
Revises: 035_remove_static_event_data
Create Date: 2026-01-14 16:32:41.231623

"""

import sqlalchemy as sa
from alembic import op

revision = "036_add_another_max_int_column"
down_revision = "035_remove_static_event_data"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("component", schema=None) as batch_op:
        batch_op.add_column(sa.Column("add_another_max", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("component", schema=None) as batch_op:
        batch_op.drop_column("add_another_max")

    # ### end Alembic commands ###
