"""empty message

Revision ID: 037_add_another_max_reference
Revises: 036_add_another_max_int_column
Create Date: 2026-01-14 17:13:28.379308

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "037_add_another_max_reference"
down_revision = "036_add_another_max_int_column"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("component", schema=None) as batch_op:
        batch_op.add_column(sa.Column("add_another_max_ref", postgresql.CITEXT(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("component", schema=None) as batch_op:
        batch_op.drop_column("add_another_max_ref")

    # ### end Alembic commands ###
