"""empty message

Revision ID: 038_add_another_iteration_ref
Revises: 037_add_another_max_reference
Create Date: 2026-01-16 06:35:57.264700

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "038_add_another_iteration_ref"
down_revision = "037_add_another_max_reference"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("component", schema=None) as batch_op:
        batch_op.add_column(sa.Column("add_another_iterate_ref", postgresql.CITEXT(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("component", schema=None) as batch_op:
        batch_op.drop_column("add_another_iterate_ref")

    # ### end Alembic commands ###
