"""Add custom expressions

Revision ID: 043_add_custom_expression
Revises: 042_remove_allow_decimals
Create Date: 2026-02-05 11:07:38.596690

"""

from alembic import op
from alembic_postgresql_enum import TableReference

revision = "043_add_custom_expression"
down_revision = "042_remove_allow_decimals"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="managed_expression_enum",
        new_values=[
            "GREATER_THAN",
            "LESS_THAN",
            "BETWEEN",
            "IS_YES",
            "IS_NO",
            "ANY_OF",
            "SPECIFICALLY",
            "IS_BEFORE",
            "IS_AFTER",
            "BETWEEN_DATES",
            "UK_POSTCODE",
            "CUSTOM",
        ],
        affected_columns=[TableReference(table_schema="public", table_name="expression", column_name="managed_name")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="managed_expression_enum",
        new_values=[
            "GREATER_THAN",
            "LESS_THAN",
            "BETWEEN",
            "IS_YES",
            "IS_NO",
            "ANY_OF",
            "SPECIFICALLY",
            "IS_BEFORE",
            "IS_AFTER",
            "BETWEEN_DATES",
            "UK_POSTCODE",
        ],
        affected_columns=[TableReference(table_schema="public", table_name="expression", column_name="managed_name")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
