"""empty message

Revision ID: 054_public_collection
Revises: 053_validation_event_types
Create Date: 2026-03-12 14:22:56.843981

"""

import sqlalchemy as sa
from alembic import op

revision = "054_public_collection"
down_revision = "053_validation_event_types"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collection", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("allow_public_sign_up", sa.Boolean(), server_default=sa.text("false"), nullable=False)
        )

    with op.batch_alter_table("organisation", schema=None) as batch_op:
        batch_op.add_column(sa.Column("trusted_email_domain", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organisation", schema=None) as batch_op:
        batch_op.drop_column("trusted_email_domain")

    with op.batch_alter_table("collection", schema=None) as batch_op:
        batch_op.drop_column("allow_public_sign_up")

    # ### end Alembic commands ###
