name: 'Run Database Migrations'
description: 'Composite Action to run Database Migration script'
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: 3.14.6

    - name: Install uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      with:
        version: "0.11.23"
        enable-cache: true

    - name: Install dependencies
      shell: bash
      run: uv sync

    - name: Run Database Migrations
      shell: bash
      run: |
        uv run scripts/run-ad-hoc-task.py --command "flask db upgrade"
