name: Deployment pipeline
run-name: Build, deploy and e2e test ${{github.ref_name}}

permissions:
  packages: write
  contents: read  # This is required for actions/checkout
  id-token: write  # This is required for authenticating with aws

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  cnb_build:
    name: Build
    uses: ./.github/workflows/package.yml
    secrets:
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      TEMP_SLACK_CHANNEL_ID: ${{ secrets.TEMP_SLACK_CHANNEL_ID }}

  deploy_dev:
    name: Deploy to dev
    needs:
      - cnb_build
    uses: ./.github/workflows/deploy.yml
    concurrency:
      group: fs-deploy-dev
      cancel-in-progress: false
    with:
      environment: dev
      ghcr_image_location: ${{ needs.cnb_build.outputs.ghcr_image_location }}
      run_e2e_tests: true
    secrets:
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      TEMP_SLACK_CHANNEL_ID: ${{ secrets.TEMP_SLACK_CHANNEL_ID }}

  deploy_test:
    name: Deploy to test
    # TODO: Strip this condition when we have dev/test/prod envs; for now, if we trigger the pipeline manually then
    #       it should only deploy to the dev env. Test env will only be deployed to on a merge (push) to main.
    if: github.event_name == 'push'
    needs:
      - cnb_build
      - deploy_dev
    uses: ./.github/workflows/deploy.yml
    concurrency:
      group: fs-deploy-test
      cancel-in-progress: false
    with:
      environment: test
      ghcr_image_location: ${{ needs.cnb_build.outputs.ghcr_image_location }}
      run_e2e_tests: true
    secrets:
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      TEMP_SLACK_CHANNEL_ID: ${{ secrets.TEMP_SLACK_CHANNEL_ID }}
