name: Deployment pipeline
run-name: Build, deploy and e2e test ${{github.ref_name}}

permissions:
  packages: write
  contents: read  # This is required for actions/checkout
  id-token: write  # This is required for authenticating with aws

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build, publish & deploy
    uses: ./.github/workflows/package.yml
    concurrency:
      group: fs-paketo-dev
      cancel-in-progress: false
    secrets:
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      TEMP_SLACK_CHANNEL_ID: ${{ secrets.TEMP_SLACK_CHANNEL_ID }}

  e2e_tests:
    name: Python E2E tests
    needs:
      - build_and_deploy
    uses: ./.github/workflows/run_e2e_tests.yml
    secrets:
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      TEMP_SLACK_CHANNEL_ID: ${{ secrets.TEMP_SLACK_CHANNEL_ID }}
