name: CI tests
run-name: CI tests

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_and_test:
    name: Build and test
    uses: ./.github/workflows/build_and_test.yml
